name: test1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11.0.27
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11.0.27'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and Push
        uses: docker/build-push-action@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          image: itpro2025/demo-app:tagname
          registry: docker.io
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.TESTDOCKER }}

          echo Add other actions to build,
          echo test, and deploy your project.
