name: test1

on: 
 push:
  branches: [main]
 pull_request:
  branches: [main]
permissions:
  contents: read
  security-events: write

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: set up JDK 17
   - uses: actions/setup-java@v4
     with:
      java-version: 4.0
      
   - name: Execute permission for gradlew
     run: chmod +x gradlew

   - name: build with gradlew
     run: ./gradlew build
   
   - name: Build and Push
     uses: docker/build-push-action@v6

   - name: Log in to Docker Hub
     uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
     with:
          image: itpro2025/demo-app:tagname
          registry: docker.io
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.TESTDOCKER }}
